---
- name: reviewboard
  hosts: all
  become: yes
  become_method: sudo
  remote_user: '{{admin_username}}'

  roles:
    - { role: common , tags: "common"} 
    - { role: apache2, tags: "apache2" }
    - { role: mysql, tags: "mysql" }
    - { role: reviewboard, tags: "reviewboard" }
    - { role: install, tags: "install"}
    - { role: end, tags: "end"}