---
# 核心任务
- name: reviewboard
  hosts: all
  become: yes
  become_method: sudo

  vars_files:
    vars/main.yml

  roles:
    - { role: role_common , tags: "role_common"} 
    - { role: role_cloud , tags: "role_cloud"} 
    - { role: role_apache, tags: "role_apache" }
    - { role: role_mysql, tags: "role_mysql" }
    - { role: reviewboard, tags: "reviewboard" }
    - { role: role_docker, tags: "role_docker" } 
    - { role: role_docker_phpmyadmin, tags: "role_docker_phpmyadmin" }
    - { role: role_init_password , tags: "role_init_password"} 
    - { role: role_preend , tags: "role_preend"} 
    - { role: role_end , tags: "role_end"} 

