---
- name: reviewboard
  hosts: all
  remote_user: root

  roles:
    - { role: common , tags: "common"} 
    - { role: apache2, tags: "apache2" }
    - { role: mysql, tags: "mysql" }
    - { role: reviewboard, tags: "reviewboard" }
    - { role: install, tags: "install" }