---

- name: Install apache2
  apt:
    name: [apache2, python-pip, libapache2-mod-wsgi]
    state: latest

- name: Create /data/wwwroot
  file: 
    path: /data/wwwroot
    state: directory
    owner: root
    group: root
    mode: 0755