---
# 服务器前置任务(ubuntu使用 Centos项目注释或删掉)
- name: main
  hosts: all
  become: yes
  become_method: sudo
  gather_facts: False
  pre_tasks:
   - name: Install Python
     raw: sudo apt update && sudo apt update && sudo apt-get -y install python


- name: reviewboard
  hosts: all
  become: yes
  become_method: sudo
  become_user: root
  

  roles:
    - { role: common , tags: "common"} 
    - { role: apache, tags: "apache" }
    - { role: mysql, tags: "mysql" }
    - { role: reviewboard, tags: "reviewboard" }
