
- name: Create database
  mysql_db:
    name: reviewboard
    state: present
    login_user: root
    login_password: 123456

- name: create reivewboard website
  shell: rb-site install /var/www/reviews.example.com