- name: create expect script
  copy:
    src: reviewboard.exp
    dest: /tmp/reviewboard.exp
    owner: root
    group: root
    mode: 0755

- name: Create reviewboard site
  shell: expect /tmp/reviewboard.exp

- name: delete reviewboard.exp
  file:
    path: /tmp/reviewboard.exp
    state: absent


- name: copy reviewboard's configuration file
  copy:
    src: /data/wwwroot/reviews.example.com/conf/apache-wsgi.conf
    dest: /etc/apache2/sites-available/000-default.conf
    remote_src: yes

- name: copy reviewboard's configuration file -2
  lineinfile:
    path: /data/wwwroot/reviews.example.com/conf/settings_local.py
    regexp: '^ALLOWED_HOSTS'
    line: "ALLOWED_HOSTS = ['*']'"
    state: present
 
- name: Change directory's permission
  shell: |
    chown -R www-data /data/wwwroot/reviews.example.com/htdocs/media/uploaded
    chown -R www-data /data/wwwroot/reviews.example.com/data
    find /data -type d -exec chmod 750 {} \;
    find /data -type f -exec chmod 640 {} \;
  notify: restart apache
